Repository GDSC-PKNU-Official/pknu-notice-back, pull requests merged in 2023-05, with the labels that each got.

#2 초기 환경 세팅
  dockerfile.dev
  package.json
  src/index.ts
  tsconfig.path.json
  yarn.lock
Labels: ⚒️ chore, ⚙️ config, 🔍 test

#4 Feat/#3: 개발에 필요한 다양한 기능 추가
  .env.vault
  jest.config.js
  package.json
  src/config/index.ts
  src/index.ts
  src/middlewares/cors.ts
  src/middlewares/error-handler.ts
  src/tests/index.test.ts
  tsconfig.path.json
  yarn.lock
Labels: ⚙️ config, ✨ feat

#8 Feat/#5: 단과대 크롤링 하기
  jest.config.js
  package.json
  src/crawling/collegeCrawling.ts
  src/tests/collegeCrawling.test.ts
  tsconfig.path.json
  yarn.lock
Labels: ✨ feat

#15 Feat/#9: 노션 API 를 활용한 건의사항 post api 구현
  .env.vault
  src/apis/suggestion/controller.ts
  src/apis/suggestion/service.ts
  src/config/index.ts
  src/index.ts
Labels: ✨ feat

#17 Feat/#14: 단과대 크롤링 개선 & 졸업요건 크롤링 추가
  src/crawling/collegeCrawling.ts
  src/crawling/graduationRequirementsCrawling.ts
  src/index.ts
  src/tests/collegeCrawling.test.ts
Labels: ✨ feat

#20 Config: mongoDB -> mysql 라이브러리로 변경
  package.json
  yarn.lock
Labels: ⚙️ config
