Repository GDSC-PKNU-Official/pknu-notice-back, pull requests merged in 2023-07, with the labels that each got.

#36 Config: EB에 배포 자동화하기 위한 액션 추가
  .github/workflows/release.yml
Labels: ⚙️ config

#34 Feat/#33: 일부 오류 해결 및 서버 최초 실행 시 데이터추가하는 로직 추가
  docker-compose.yml
  sqls/createTable.sql
  src/apis/notice/controller.ts
  src/db/data/handler.ts
  src/hooks/startCrawlingData.ts
  src/index.ts
Labels: ✨ feat, 🧑‍🔧 refactor

#39 Fix/#38: 공지사항 요청 하는 함수 에러 핸들링 추가
  src/apis/notice/controller.ts
  src/apis/notice/service.ts
Labels: 🛠 fix

#41 Config: CLIENT_PATH 환경변수 수정
  .env.vault
Labels: ⚙️ config

#43 Fix: 시각디자인학과 공지사항 가져오는 코드 추가
  src/crawling/noticeCrawling.ts
Labels: 🛠 fix

#47 Fix: 공간정보시스템공학과 element 태그로 고정과 일반 공지사항 구분하도록 변경
  src/crawling/noticeCrawling.ts
Labels: 🛠 fix, 🧑‍🔧 refactor

#49 Feat/#48: 매일 오전 2시에 공지사항 크롤링하는 훅 추가
  package.json
  src/db/data/handler.ts
  src/hooks/cronNoticeCrawling.ts
  src/hooks/startCrawlingData.ts
  src/index.ts
  yarn.lock
Labels: ⚙️ config, ✨ feat, 🛠 fix

#54 Feat/#53: 깃허브 액션으로 배포 자동화 구현하기
  .github/workflows/Deploy.yml
  .github/workflows/release.yml
  src/db/index.ts
  src/index.ts
  src/tests/dbConnect.test.ts
Labels: ✨ feat

#56 Feat/#55: 학교 공지사항 반환하는 엔드포인트 추가
  src/apis/notice/controller.ts
  src/apis/notice/service.ts
Labels: ✨ feat
