Repository GDSC-PKNU-Official/pknu-notice-back, pull requests merged in 2023-08, with the labels that each got.

#58 Refactor: 공지사항을 고정, 일반 나눠서 반환하도록 변경
  src/apis/notice/service.ts
Labels: 🧑‍🔧 refactor

#65 Fix: 시각디자인학과 크롤링 가능하도록 수정
  src/crawling/noticeCrawling.ts
Labels: 🛠 fix

#69 Fix/#68: 특정 공지사항 크롤링 시 제목에 내용도 같이 크롤링되는 문제 수정
  src/crawling/noticeCrawling.ts
  src/db/data/handler.ts
Labels: 🛠 fix

#71 Fix: 신설 학과는 크롤링하지 않도록 수정
  src/crawling/collegeCrawling.ts
Labels: 🛠 fix

#73 Fix: 학교 공지사항 처리 에러 해결
  src/apis/notice/controller.ts
Labels: 🛠 fix

#74 Feat/#59: 졸업요건 크롤링 후 db에 저장 & 엔드포인트 설정
  src/apis/graduation/controller.ts
  src/apis/graduation/service.ts
  src/constants/graduation.ts
  src/crawling/graduationRequirementsCrawling.ts
  src/db/data/graduation.ts
  src/hooks/startCrawlingData.ts
  src/index.ts
  src/middlewares/cors.ts
Labels: ⚙️ config, ✨ feat

#77 Feat: 배포 후 졸업요건 크롤링 함수 추가
  src/index.ts
Labels: ✨ feat

#84 Feat/#83: slack 으로 알림을 받을 수 있는 훅 추가
  src/config/index.ts
  src/crawling/noticeCrawling.ts
  src/db/data/handler.ts
  src/hooks/cronNoticeCrawling.ts
  src/hooks/notificateToSlack.ts
Labels: ✨ feat

#91 Fix/#90: RDS 용량문제 해결
  src/db/data/handler.ts
  src/db/table/createTables.ts
Labels: 🛠 fix

#87 Fix/#86: 배포 서버의 불필요한 로그 제거
  src/db/data/handler.ts
  src/hooks/cronNoticeCrawling.ts
  src/index.ts
Labels: ✨ feat

#93 Feat: 매일 학교 공지사항도 크롤링하여 DB에 저장하도록 추가
  src/hooks/cronNoticeCrawling.ts
Labels: ✨ feat

#89 Feat/#88: 새 공지가 올라오면 구독한 유저들에게 push 알림 주도록 추가
  src/apis/subscribe/service.ts
  src/db/data/handler.ts
  src/hooks/cronNoticeCrawling.ts
Labels: ✨ feat
